export const GET_PRODUCTS = 'GET_PRODUCTS';
export const STORE_PRODUCT = 'STORE_PRODUCT';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const STORE_CATEGORIES = 'STORE_CATEGORIES';
